# Generated by Django 4.2 on 2023-05-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis_codes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='abbreviated_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='full_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='diagnosiscategory',
            name='description',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='icdversion',
            name='description',
            field=models.CharField(max_length=400),
        ),
    ]
